"""CPU-only binding of fresh worker identity to the fixed exploratory release."""
import hashlib
import json
import os
from pathlib import Path
import re

ROOT = Path('/research/d7/spc/yzyang4/forets-next-config-20260911-4h_0y6b4')
RELEASE_SHA = 'e7c64f43032901716f4f3d5abf75a3e7d15f6417bd44e7e6e37b5fc5f8983706'


def release(raw):
    if RELEASE_SHA is None or hashlib.sha256(raw).hexdigest() != RELEASE_SHA:
        raise RuntimeError('fixed exploration release absent or changed')
    return json.loads(raw)


def context(environment, *, root=ROOT):
    """Resolve exact pool-owned identity without touching a GPU or credentials."""
    path = Path(environment.get('FORETS_NATIVE_RELEASE', ''))
    if not path.is_absolute() or path.is_symlink():
        raise ValueError('explicit release file required')
    spec = release(path.read_bytes())
    if str(root) != spec['package']:
        raise ValueError('release names another package')
    identity = Path(environment.get('DOJO_WORKER_IDENTITY_PATH', ''))
    if not identity.is_absolute() or identity.is_symlink():
        raise ValueError('explicit worker identity required')
    actual = identity.resolve(strict=True)
    pool = root.resolve(strict=True)/'runs'/'srun_pool'
    relative = actual.relative_to(pool)
    if (len(relative.parts) != 3 or not re.fullmatch('[0-9a-f]{12}', relative.parts[0])
            or relative.parts[1] != 'identities'):
        raise ValueError('identity outside fixed pool')
    row = json.loads(actual.read_text())
    job, step = environment.get('SLURM_JOB_ID', ''), environment.get('SLURM_STEP_ID', '')
    if (not job.isdigit() or not step.isdigit() or row.get('allocation_id') != job
            or row.get('step_id') != step or row.get('full_step_id') != job+'.'+step
            or row.get('attempt') != 1):
        raise ValueError('worker identity differs from live step')
    prepared_raw = (root/'prepared.json').read_bytes()
    from forets_block_controller_20260911 import PREPARED_SHA
    if hashlib.sha256(prepared_raw).hexdigest() != PREPARED_SHA:
        raise ValueError('fixed preparation changed')
    prepared = json.loads(prepared_raw)
    selected = [r for r in prepared['run_configs'] if r['run_id'] == row.get('run_id')]
    if len(selected) != 1:
        raise ValueError('unplanned run identity')
    run_id = selected[0]['run_id']
    group = sorted(r['run_id'] for r in prepared['run_configs'] if r['block'] == selected[0]['block'])
    key = hashlib.sha256('\n'.join(group).encode()).hexdigest()[:12]
    stem = re.sub(r'[^A-Za-z0-9_.-]+', '-', run_id).strip('-.')[:64]+'-'+hashlib.sha256(run_id.encode()).hexdigest()[:10]
    if relative.parts[0] != key or actual.name != stem+'.attempt-1.json':
        raise ValueError('identity not generated by fixed fresh pool')
    return actual


class NativeWorkerEnvironment:
    """Mixin ahead of RuntimePoolControl; only child startup environment changes."""
    def _launch(self, run_id):
        identity = self._identity_path(run_id, 1)
        additions = dict(DOJO_WORKER_IDENTITY_PATH=str(identity),
            FORETS_NATIVE_RELEASE=str(self.native_release_path),
            FORETS_SOURCE_COMMIT=self.native_controller_commit,
            PATH=str(self.native_code_dir/'bin')+os.pathsep+os.environ.get('PATH', ''))
        if os.environ.get('FORETS_NATIVE_INTEGRATION_ROOT'):
            raise RuntimeError('production must not inherit integration mode')
        previous = {k:os.environ.get(k) for k in additions}
        try:
            os.environ.update(additions)
            return super()._launch(run_id)
        finally:
            for key, value in previous.items():
                if value is None: os.environ.pop(key, None)
                else: os.environ[key] = value
