_target_: dojo.config_dataclasses.interpreter.jupyter.JupyterInterpreterConfig

container_runtime: singularity
superimage_directory: ${get_superimage_dir:}
superimage_version: "2026-07-macos-v1"

read_only_overlays: []

env:
    HF_HUB_OFFLINE: "1"
    NLTK_DATA: /root/.nltk_data
