_target_: dojo.config_dataclasses.client.base.ClientConfig
api: litellm
model_id: "qwen3-coder-flash"
base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
use_azure_client: False
provider: openai
